[package]
name = "fortitude-webview"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3", default-features = false, features = ["std"] }
gtk = { package = "gtk4", version = "0.7" }
webkit = { package = "webkit6", version = "0.2" }
